---
title: "Exercises"
editor: 
    render-on-save: true
---

## Instructions

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(bslib)
library(shiny)
accordion(
  class = "mb-5",
  accordion_panel(
    title = "Exercise 1: a palmer penguins, single stack.",
    tags$ol(
      tags$li(
        p(
            "Click on the stack",
            tags$strong("+"),
            "button (top right corner)."
        )
      ),
      tags$li(
        p(
            "Add a",
            tags$code("palmer_penguins"),
            "block. You may search in the list."
        )
      ),
      tags$li(
        p(
            "Add a new",
             tags$code("filter_block"),
             "selecting", tags$var("sex"), "as", tags$strong("column"), "and", tags$var("female"), "as", tags$strong("value"), ". Click on run."
        )
      ),
      tags$li(
        p(
            "Add a new", tags$code("ggplot_block"), ". Select", tags$var("x"), "and", tags$var("y") , "wizely."
        )
      ),
      tags$li(
        p(
            "Add a new", tags$code("geompoint_block"), ". You may change", tags$var("shape") , "and", tags$var("color"), "."
        )
      ),
      tags$li("You can remove and re-add blocks as you like ..."),
      tags$li("Export the stack code and try to run it.")
    )
  ),
  accordion_panel(
    title = "Exercise 2: distribution of age, single stack.",
    tags$ol(
      tags$li(
        p("Click on the", tags$strong("+") , "stack button (top right corner).")
      ),
      tags$li(
        p(
            "Add a", tags$code("customdata_block"), "with", tags$var("demo"), "as", tags$strong("selected"), "dataset."
        )
      ),
      tags$li(
        p(
            "Add a",  tags$code("ggplot_block") , "with", tags$var("AGE"), " as variable for the",  tags$var("x"), "axis."
        )
      ),
      tags$li(
        p("Add a", tags$code("geomhistogram_block"), ". You can change the parameters.")
      ),
      tags$li(
        p(
            "Add a",  tags$code("labs_block"), "with", tags$code("title = 'Distribution of Age'"), tags$code("x = 'Age (Years)'"), "and",  tags$code("y = 'Count'"), "as settings."
        )
      ),
      tags$li(
        p("Add a", tags$code("theme_block"), ".")
      ),
      tags$li(
        p("Add a", tags$code("scalefillbrewer_block"), ".")
      )
    )
  ),
  accordion_panel(
    title = "Exercise 3: a palmer penguins workspace.",
    tags$ol(
      tags$li(
        p("Click on", tags$strong("Add stack"), ".")
      ),
      tags$li(
        p("From the new stack: click on", tags$strong("+"), "to add a new", tags$code("result_block"), ".")
      ),
      tags$li(
        p(
            "Add a new",
             tags$code("filter_block"),
             "selecting", tags$var("sex"), "as", tags$strong("column"), "and", tags$var("female"), "as", tags$strong("value"), ". Click on run."
        )
      ),
      tags$li("Notice how the result block of the second stack changes."),
      tags$li(
        p(
            "Add a new", tags$code("ggplot_block"), ". Select", tags$var("x"), "and", tags$var("y") , "wizely."
        )
      ),
      tags$li(
        p(
            "Add a new", tags$code("geompoint_block"), ". You may change", tags$var("shape") , "and", tags$var("color"), "."
        )
      )
    )
  ),
  accordion_panel(
    title = "Exercise 4: joining data.",
    tags$ol(
      tags$li(
        p("Click on", tags$strong("Add stack"), ".")
      ),
      tags$li(
        p("From the new stack: click on", tags$strong("+"), "to add a new", tags$code("customdata_block"), " with", tags$var("lab") , " as selected data.")
      ),
      tags$li(
        p("Click on", tags$strong("Add stack"), ".")
      ),
      tags$li(
        p(
            "Add a new",
             tags$code("join_block"),
             "selecting", tags$var("lab_data"), "as", tags$strong("Stack"), "and", tags$var("inner"), "as", tags$strong("type"), "and", tags$var("c('STUDYID', 'USUBJID')"), "as", tags$strong("by"), ". Click on run."
        )
      )
    )
  ),
  accordion_panel(
    title = "Exercise 5: 'Hemoglobin by Visit plot' workspace.",
    tags$ol(
      tags$li(
                p("Click on", tags$strong("Add stack"), "then add a", tags$code("result_block"), "selecting the 'hb_data' stack.")
            ),
            tags$li(
                p("Add a", tags$code("ggplot_block"), "with", tags$code("x = 'VISIT"), "and", tags$code("y = 'Mean"), "as aesthetics.")
            ),
            tags$li(
                p("Add a", tags$code("geompoint_block"), "with", tags$code("func = c('color', 'shape')"), "and", tags$var("ACTARM"), "as variable for each aesthetic.")
            ),
            tags$li(
                p("Add a", tags$code("geomerrorbar_block"), "with", tags$code("ymin = ymin"), tags$code("ymax = ymax"), "and", tags$code("color = ACTARM"), ".")
            ),
            tags$li(
                p("Add a", tags$code("geomline_block"), "with", tags$code("group = ACTARM"), "and", tags$code("color = ACTARM"), ".")
            ),
            tags$li(
                p("Add a", tags$code("labs_block"), "with", tags$code("title = 'Mean and SD of Hemoglobin by Visit'"), tags$code("x = 'Visit Label'"), "and", tags$code("y = 'Hemoglobin (g/dL)'"), ".")
            ),
            tags$li(
                p("Add a", tags$code("theme_block"), ".")
            )
    )
  )
)
```

## Playground

:::{.column-screen-inset}
```{r, echo=FALSE}
source("./assets/R/tools.R")
create_link_iframe("https://rinpharma2024.rinterface.com/")
```
:::