on:
  workflow_dispatch:
  push:
    branches: main
  pull_request:
    branches: main

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.5.57

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Avoid bundling Shinylive packages
        run: echo "SHINYLIVE_WASM_PACKAGES=0" >> $GITHUB_ENV

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: "./exercises"
          extra-packages: |
            posit-dev/r-shinylive
            any::knitr
            any::rmarkdown
          cache-version: 2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
